[workspace]
resolver = "2"
members = [
    "crates/topo-core",
    "crates/topo-geom",
    "crates/topo-timber",
    "crates/topo-draw",
    "crates/topo-analysis",
    "crates/topo-cli",
    "crates/topo-wasm",
    "crates/topo-script",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
topo-core = { path = "crates/topo-core" }
topo-geom = { path = "crates/topo-geom" }
topo-draw = { path = "crates/topo-draw" }
topo-timber = { path = "crates/topo-timber" }
topo-analysis = { path = "crates/topo-analysis" }
topo-script = { path = "crates/topo-script" }
